# 使用说明 V3.4.0
# 1. 使用docker-compose  宿主机不需要配置host来发现
# 2. 无需修改源码，根目录  docker-compose up 即可
# 3. 静静等待服务启动

version: '2'
services:
  demo-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: demo-mysql
    image: demo-mysql
    ports:
      - 3306:3306
    volumes:
      - ./pigx-mysql:/var/lib/mysql
    command: --lower_case_table_names=1
  zookeeper:
    image: zookeeper:3.4.13
    restart: always
  spring-boot-dubbo-consumer:
    build:
      context: ./
      dockerfile: spring-boot-dubbo-consumer/Dockerfile
    restart: always
    image: spring-boot-dubbo-consumer
    container_name: spring-boot-dubbo-consumer
    ports:
      - 9091:9091
  spring-boot-dubbo-provider:
    build:
      context: ./
      dockerfile: spring-boot-dubbo-provider/Dockerfile
    restart: always
    image: spring-boot-dubbo-provider
    container_name: spring-boot-dubbo-provider
    ports:
      - 9092:9092